feat: provides db
qroques/symfony-template pull request #3
Opened 2023-04-21 07:21 UTC by FlorianQgb

2023-04-21 07:36 UTC, clementvtrd requested changes

2023-04-21 07:36 UTC, clementvtrd commented on makefile
> -install-dev: copy-env ## Install symfony
Are you sure you want to remove the `copy-env`? When the default env will be initialize?

2023-04-21 08:50 UTC, FlorianQgb commented on makefile
> -install-dev: copy-env ## Install symfony
This was causing the command not to work on my macOS
And the doc explicitly tells to first run the make copy-env, don't know if we should keep it or not 🤷

2023-04-21 08:51 UTC, clementvtrd approved these changes

2023-04-21 08:51 UTC, clementvtrd commented on makefile
> -install-dev: copy-env ## Install symfony
If the doc explicitly tells to run it first, no need to keep it here indeed

2023-04-24 07:29 UTC, qroques approved these changes

2023-04-24 08:10 UTC, ErwannLeRoux approved these changes

2023-04-24 08:11 UTC, merged